// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUjeqr_tJ8ZQwf9wRpAIpfgBY8pGYm0f4',
    appId: '1:530082175833:web:531a8f54df01d0fe2d4a48',
    messagingSenderId: '530082175833',
    projectId: 'stuedu-e34b7',
    authDomain: 'stuedu-e34b7.firebaseapp.com',
    storageBucket: 'stuedu-e34b7.firebasestorage.app',
    measurementId: 'G-YGYK0ZM9H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tAIfs-X8atpyY5elRXBVggRyB0w9oJA',
    appId: '1:530082175833:android:744ff1e79971140c2d4a48',
    messagingSenderId: '530082175833',
    projectId: 'stuedu-e34b7',
    storageBucket: 'stuedu-e34b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2j8hxT8hLTHYti8BRKieS17yDA4ZFynU',
    appId: '1:530082175833:ios:962f13da2b2a01cb2d4a48',
    messagingSenderId: '530082175833',
    projectId: 'stuedu-e34b7',
    storageBucket: 'stuedu-e34b7.firebasestorage.app',
    iosClientId: '530082175833-6tmqnh7mb3l5hsanbj85n81okd98m90b.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2j8hxT8hLTHYti8BRKieS17yDA4ZFynU',
    appId: '1:530082175833:ios:962f13da2b2a01cb2d4a48',
    messagingSenderId: '530082175833',
    projectId: 'stuedu-e34b7',
    storageBucket: 'stuedu-e34b7.firebasestorage.app',
    iosClientId: '530082175833-6tmqnh7mb3l5hsanbj85n81okd98m90b.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUjeqr_tJ8ZQwf9wRpAIpfgBY8pGYm0f4',
    appId: '1:530082175833:web:2899e51b9bc65e182d4a48',
    messagingSenderId: '530082175833',
    projectId: 'stuedu-e34b7',
    authDomain: 'stuedu-e34b7.firebaseapp.com',
    storageBucket: 'stuedu-e34b7.firebasestorage.app',
    measurementId: 'G-WEHZHYT9C5',
  );
}
